#!/bin/bash

#SBATCH --partition=3090,2080ti                    #Selecting partition based on GPU type
# weka for some reason isn't helping either #SBATCH --constraint=fs_weka
#SBATCH --job-name="lircst-data"                 #Name of Jobs (displayed in squeue)
#SBATCH --nodes=1                           #No of nodes to run job
#SBATCH --cpus-per-task=4                   #No of cores to use per node (default - 4 CPU cores per GPU selected)
#SBATCH --time=71:59:00                     #Maximum time for job to run
#SBATCH --mem=16G                           #Amount of memory per node
#SBATCH --gpus=0                            #Selecting n x GPUs
#SBATCH --output=/mnt/fast/nobackup/users/sy00917/dev/lircst-data/logs/slurm.%j.%N.out            #Output file for stdout (optional)
#SBATCH --error=/mnt/fast/nobackup/users/sy00917/dev/lircst-data/logs/slurm.%j.%N.err             #Error file for stderr (optional)
# P.S slurm probably won't make directories for you (logging etc.)
# P.S those directories are relative to where you sent off your submit script


PROJECT_ROOT="/mnt/fast/nobackup/users/sy00917/dev/lircst-data"
BUILD_DIR="${PROJECT_ROOT}/build"

cd "${BUILD_DIR}" || exit 1
source /mnt/fast/nobackup/users/sy00917/miniconda3/etc/profile.d/conda.sh
conda activate lircst-data

# Strict mode only after we activate conda (as there's some unsafe stuff happening there)
set -euo pipefail

echo "Checking/building project..."

cmake -DGeant4_DIR=$CONDA_PREFIX/lib/Geant4-* ../
make -j4

echo "Build complete: $(date)"