#!/bin/bash

#SBATCH --partition=3090,2080ti                    #Selecting partition based on GPU type
# weka for some reason isn't helping either #SBATCH --constraint=fs_weka
#SBATCH --job-name="lircst-data"                 #Name of Jobs (displayed in squeue)
#SBATCH --nodes=1                           #No of nodes to run job
#SBATCH --cpus-per-task=20                  #No of cores to use per node (default - 4 CPU cores per GPU selected)
#SBATCH --time=71:59:00                     #Maximum time for job to run
#SBATCH --mem=16G                           #Amount of memory per node
#SBATCH --gpus=0                            #Selecting n x GPUs
#SBATCH --output=/mnt/fast/nobackup/users/sy00917/dev/lircst-data/logs/slurm.%j.%N.out            #Output file for stdout (optional)
#SBATCH --error=/mnt/fast/nobackup/users/sy00917/dev/lircst-data/logs/slurm.%j.%N.err             #Error file for stderr (optional)
# P.S slurm probably won't make directories for you (logging etc.)
# P.S those directories are relative to where you sent off your submit script


echo "Starting job on $(date), Info:"
echo $SLURM_JOB_ID
echo $SLURM_SUBMIT_DIR
# echo $SLURM_JOB_NODELIST
# echo $SLURM_NTASKS
# echo $SLURM_JOB_ID
echo $SLURM_ARRAY_TASK_ID


THETA_INDEX="${SLURM_ARRAY_TASK_ID}"

GENERATE_PHAN=false

if [[ "${GENERATE_PHANTOM}" == "true" ]] && \
   [[ "${SLURM_ARRAY_TASK_ID}" -eq "${SLURM_ARRAY_TASK_MIN}" ]]; then

    GENERATE_PHAN=true
fi

echo "Seed:              ${SEED}"
echo "Events:            ${EVENTS}"
echo "Theta index:       ${THETA_INDEX}"
echo "Generate phantom?: ${GENERATE_PHAN}"

PROJECT_ROOT="/mnt/fast/nobackup/users/sy00917/dev/lircst-data"

cd "${PROJECT_ROOT}/build" || exit 1
source /mnt/fast/nobackup/users/sy00917/miniconda3/etc/profile.d/conda.sh
conda activate lircst-data

# Strict mode only after we activate conda (as there's some unsafe stuff happening there)
set -euo pipefail

./lircstData "${SEED}" "${THETA_INDEX}" "${EVENTS}" "${GENERATE_PHAN}"

